### ISSUE TITLE
Backward compatibility to run on Py3.5.2

### ISSUE THREAD

**Issue by hvsarma** [wayfair/pylift#12]
This module runs well on python 3.6x. & 3.7.
1. Please make it run on 3.5.2 for my use-case (on databricks).
2. Egg distribution is ideal.

**Comment by rsyi** [comment]
Hi Harish! Sorry for the delay. On account of [this](https://stackoverflow.com/questions/50126814/ignoring-ensurepip-failure-pip-requires-ssl-tls-error-in-ubuntu-18-04/50860976#50860976), I've had a hell of a time installing python 3.5.2 locally. I'm able to install python 3.5.3, but I cannot recreate any errors with this version. If you don't mind, could you paste the traceback and the command you run that causes the problem?

**Comment by rsyi** [comment]
Closed. Feel free to reopen if you'd still like this to be addressed.
