### ISSUE TITLE
Pickling Error when calling .randomized_search on up

### ISSUE THREAD

**Issue by khaashif** [wayfair/pylift#18]

**Comment by rsyi** [comment]
Hi Khaashif! It looks like you closed it. Was this on purpose? Did you figure it out?

**Comment by khaashif** [comment]
Hi Rob,

Yeah I closed it, turns out the pickling error is as a result of
insufficient resources for the python client...given that it's ran on work
PCs there are slight restrictions on admin privileges so I'm working on a
way around it.

Will contact back if there are any other questions!

Cheers,

Khaashif
