### ISSUE TITLE
Latex is not rendering on documentation

### ISSUE THREAD

**Issue by zhouzhuojie** [wayfair/pylift#27]
https://pylift.readthedocs.io/en/latest/introduction.html

For example:

![image](https://user-images.githubusercontent.com/658840/63318742-56fc4100-c2cc-11e9-885f-202b0285d471.png)

**Comment by rsyi** [comment]
Thanks for pointing this out.

Looks like there was a recent update that affected the functionality of native mathjax notation on sphinx. I'll go ahead and convert the files to the native .rst format and fix this asap!

(https://github.com/readthedocs/recommonmark/issues/133)

**Comment by rsyi** [comment]
Fixed on readthedocs, so feel free to start reading the corrected version.
PR to update the Wayfair repo: https://github.com/wayfair/pylift/pull/29

**Comment by zhouzhuojie** [comment]
thanks!
